# Basic augmentation configuration
level: light  # Options: none, light, medium, heavy
train:
  random_rotation:
    degrees: 360
    p: 0.5
  random_flip:
    horizontal: true
    vertical: true
    p: 0.5
  random_scale:
    scale_limit: 0.1
    p: 0.5
  random_brightness_contrast:
    brightness_limit: 0.2
    contrast_limit: 0.2
    p: 0.5
  elastic_transform:
    alpha: 50
    sigma: 5
    p: 0.3
val:
  normalize_only: true
test:
  normalize_only: true
  tta:
    enabled: false
    num_augmentations: 5