# Medium augmentation configuration (default)
level: medium
train:
  random_rotation:
    degrees: 90
    p: 0.5
  random_flip:
    horizontal: true
    vertical: true
    p: 0.5
  random_scale:
    scale_limit: 0.1
    p: 0.3
  random_brightness_contrast:
    brightness_limit: 0.2
    contrast_limit: 0.2
    p: 0.3
  elastic_transform:
    alpha: 50
    sigma: 5
    p: 0.3
  microscopy_augmentation:
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]
    noise_std: 0.02
    blur_sigma_range: [0, 1.0]
    p: 0.5
val:
  normalize_only: true
test:
  normalize_only: true
  tta:
    enabled: false
    num_augmentations: 5