defaults:
  - base_cnn

name: efficientnet_b0
architecture: cnn
_target_: src.models.cnn.efficientnet.EfficientNetB0

# Model parameters
in_channels: 1  # Grayscale CARS images

# EfficientNet-B0 specific parameters
dropout_rate: 0.2
drop_connect_rate: 0.2

# Training parameters (optimized for EfficientNet-B0)
learning_rate: 0.001
weight_decay: 0.001  # Lower than ResNet due to built-in regularization

# Quality-aware preprocessing
quality_aware: true

# Feature extraction
pool_type: avg  # EfficientNet uses global average pooling by default