defaults:
  - base_cnn

name: efficientnet_b2
architecture: cnn
_target_: src.models.cnn.efficientnet.EfficientNetB2

# Model parameters
in_channels: 1  # Grayscale CARS images

# EfficientNet-B2 specific parameters
dropout_rate: 0.3  # Higher dropout for larger model
drop_connect_rate: 0.2

# Training parameters (optimized for EfficientNet-B2)
learning_rate: 0.0005  # Lower for larger model
weight_decay: 0.001

# Quality-aware preprocessing
quality_aware: true

# Feature extraction
pool_type: avg  # EfficientNet uses global average pooling by default