defaults:
  - base_cnn

name: efficientnet_b1
_target_: src.models.cnn.efficientnet.EfficientNetB1

# Model parameters
in_channels: 1  # Grayscale CARS images

# EfficientNet-B1 specific parameters
dropout_rate: 0.2
drop_connect_rate: 0.2

# Training parameters (optimized for EfficientNet-B1)
learning_rate: 0.0008  # Slightly lower for larger model
weight_decay: 0.001

# Quality-aware preprocessing
quality_aware: true

# Feature extraction
pool_type: avg  # EfficientNet uses global average pooling by default