name: resnet34
architecture: cnn
_target_: src.models.cnn.resnet.ResNet34

# Model parameters
num_classes: ${dataset.num_classes}
in_channels: 1  # Grayscale CARS images
pretrained: true
freeze_backbone: false

# Architecture-specific parameters
dropout_rate: 0.25  # Slightly higher for deeper model
hidden_dim: 512

# Training parameters
learning_rate: 0.0008  # Slightly lower for deeper model
weight_decay: 0.01

# Quality-aware preprocessing
quality_aware: true

# Feature extraction
use_attention: false
pool_type: avg  # avg or max