# defaults:
#   - cnn_base_defaults # Removed

# Inlined content from cnn_base_defaults.yaml:
architecture: cnn
name: resnet18 # Overrides '???'
freeze_backbone: false
# quality_aware: false # This line (from inlined base) is removed to avoid duplication. The specific value below will be used.

# Original resnet18 content:
_target_: src.models.cnn.resnet.ResNet18

# Model parameters
in_channels: 1  # Grayscale CARS images

# Architecture-specific parameters
dropout_rate: 0.2
hidden_dim: 512

# Training parameters
learning_rate: 0.001
weight_decay: 0.01

# Quality-aware preprocessing
quality_aware: true # Overrides 'false' from inlined base

# Feature extraction
use_attention: false
pool_type: avg  # avg or max