# defaults:
#  - cnn_base_defaults # Removed

# Inlined content from cnn_base_defaults.yaml:
architecture: cnn
name: resnet50 # Overrides '???'
architecture: cnn
freeze_backbone: false
# quality_aware: false # This line (from inlined base) is removed to avoid duplication. The specific value below will be used.

# Original resnet50 content:
_target_: src.models.cnn.resnet.ResNet50

# Model parameters
in_channels: 1  # Grayscale CARS images

# Architecture-specific parameters
dropout_rate: 0.3  # Higher dropout for larger model
hidden_dim: 512

# Training parameters
learning_rate: 0.0005  # Lower learning rate for larger model
weight_decay: 0.01

# Quality-aware preprocessing
quality_aware: true # Overrides 'false' from inlined base

# Feature extraction
use_attention: false
pool_type: avg  # avg or max

# Note: ResNet50 has 25.6M parameters vs ResNet18's 11.2M
# May need smaller batch size if memory issues occur
# batch_size: 24  # Uncomment if needed