defaults:
  - base_cnn

name: resnet18
_target_: src.models.cnn.resnet.ResNet18

# Model parameters
in_channels: 1  # Grayscale CARS images

# Architecture-specific parameters
dropout_rate: 0.2
hidden_dim: 512

# Training parameters
learning_rate: 0.001
weight_decay: 0.01

# Quality-aware preprocessing
quality_aware: true

# Feature extraction
use_attention: false
pool_type: avg  # avg or max