# @package _group_
# Base model configuration - common settings for all models
name: ??? # To be overridden by specific model configs (e.g., resnet50, vit_base)
num_classes: 2 # Example, adjust if different
architecture: ??? # e.g., cnn, vit - to be overridden
pretrained: true

# Other common model parameters can go here
# Example:
# global_pool: 'avg'