name: CARS_Thyroid
data_path: "data/raw"  # Direct path instead of interpolation, renamed from 'path'
image_size: 224
patch_size: 256
patch_overlap: 0.1
num_classes: 2
class_names:
  - normal
  - cancerous
split_ratio:
  - 0.7
  - 0.15
  - 0.15
patient_level_split: true
normalize: false
cache: false
num_workers: 0
pin_memory: true
fold: 1
