name: CARS_Thyroid
path: "data/raw"  # Direct path instead of interpolation
image_size: 256
patch_size: 256
patch_overlap: 0.1
num_classes: 2
class_names:
  - normal
  - cancerous
split_ratio:
  - 0.7
  - 0.15
  - 0.15
patient_level_split: true
normalize: true
cache: false
num_workers: 0
pin_memory: true
