name: vit_medical_strong
batch_size: 24  # Smaller batch for stronger augmentation
num_epochs: 300
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.1  # Stronger regularization
  betas: [0.9, 0.999]
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 300
  eta_min: 1e-6
loss:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.15  # More smoothing
early_stopping:
  patience: 40
  min_delta: 0.001
  mode: max
  monitor: val_acc
gradient_clip_val: 0.5  # Stronger clipping
accumulate_grad_batches: 2  # Effective batch size = 48
precision: "16-mixed"

# Very strong augmentation
augmentation:
  randaugment:
    n: 3
    m: 14  # Maximum strength
  mixup_alpha: 0.8
  cutmix_alpha: 1.0
  cutmix_prob: 0.7  # Higher probability
  use_quality_aware: true
  quality_threshold: 0.6
  patch_drop_prob: 0.1

# Stochastic depth
drop_path_rate: 0.2

# Progressive augmentation
progressive_augmentation:
  enabled: true
  start_epoch: 0
  end_epoch: 100
  start_magnitude: 5
  end_magnitude: 14
