defaults:
  - model: resnet50
  - dataset: cars
  - training: standard
  - augmentation: basic
  - trainer: default
  - _self_

experiment_name: "${model.name}_${dataset.name}_${now:%Y-%m-%d_%H-%M-%S}"
seed: 42
device: auto

# Use simple relative paths instead of Hydra interpolations
paths:
  data_dir: "data"
  log_dir: "logs"
  checkpoint_dir: "checkpoints"

wandb:
  project: "thyroid-classification"
  entity: null
  tags:
    - ${model.architecture}
    - ${dataset.name}
  mode: online